### ISSUE TITLE
play-components concept & updates

### ISSUE THREAD

**Issue by serapath** [playproject-io/play-components#1]
## `@todo`
* [ ] improve button component
* [ ] impove input-integer component
* [ ] improve component styleguide

---
